# Generated by Django 5.2.7 on 2025-10-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(blank=True, max_length=15, null=True)),
                ('hire_date', models.DateField()),
                ('job_title', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
